#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import rospy

from migrave_game_emotions.migrave_game_emotions import MigraveGameEmotions

if __name__ == "__main__":
    rospy.init_node("migrave_game_emotions")
    game_config_dir_path = rospy.get_param("~game_config_dir_path", "")
    game_id = rospy.get_param("~game_id", "emotions")
    game_status_topic = rospy.get_param("~game_status_topic",
                                        "/migrave_game_emotions/status")
    game_answer_topic = rospy.get_param("~game_answer_topic",
                                        "/migrave_game_emotions/answer")
    game_performance_topic = rospy.get_param("~game_performance_topic",
                                             "/migrave/game_performance")
    game = MigraveGameEmotions(game_config_dir_path=game_config_dir_path,
                               game_id=game_id,
                               game_status_topic=game_status_topic,
                               game_answer_topic=game_answer_topic,
                               game_performance_topic=game_performance_topic)
    while not rospy.is_shutdown():
        rospy.sleep(0.1)
